TIC_TAC_TOE_PLAYER_NUM = 2
TIC_TAC_TOE_BOARD_LENGTH = 3
TIC_TAC_TOE_BOARD_WIDTH = 3
TIC_TAC_TOE_VALID_ACTIONS_INPUT = ["1","2","3"]

CHECKERS_PLAYER_NUM = 2
CHECKERS_BOARD_LENGTH = 8
CHECKERS_BOARD_WIDTH = 8
CHECKERS_STARTING_ROWS_NUM = 3